### ISSUE TITLE
Get an error when running on Ubuntu x86

### ISSUE THREAD

**Issue by jobcher** [szpnygo/gtc#2]
panic: Unsupported CPU, maybe it's too old to run Sonic.

goroutine 1 [running]:
github.com/bytedance/sonic/internal/native.init.0()
	/home/runner/go/pkg/mod/github.com/bytedance/sonic@v1.5.0/internal/native/dispatch_amd64.go:164 +0x30a

**Comment by szpnygo** [comment]
https://github.com/bytedance/sonic/issues/255

The GTC server(gogs) use the sonic
I'm not sure if sonic should be deleted for this situation, it's faster than the go original json
